//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.24 at 10:46:18 PM IST 
//


package utopia.sphnx.core.support.xmlmapping.controlmap;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ExecutionMap"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "executionMap"
})
@XmlRootElement(name = "ControlMap")
public class ControlMap {

    @XmlElement(name = "ExecutionMap", required = true)
    protected ExecutionMap executionMap;

    /**
     * Gets the value of the executionMap property.
     * 
     * @return
     *     possible object is
     *     {@link ExecutionMap }
     *     
     */
    public ExecutionMap getExecutionMap() {
        return executionMap;
    }

    /**
     * Sets the value of the executionMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExecutionMap }
     *     
     */
    public void setExecutionMap(ExecutionMap value) {
        this.executionMap = value;
    }

}
