//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.26 at 06:19:31 PM IST 
//


package utopia.sphnx.core.support.xmlmapping.testcases;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}TestRun"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "testRun"
})
@XmlRootElement(name = "Execution")
public class Execution {

    @XmlElement(name = "TestRun", required = true)
    protected TestRun testRun;

    /**
     * Gets the value of the testRun property.
     * 
     * @return
     *     possible object is
     *     {@link TestRun }
     *     
     */
    public TestRun getTestRun() {
        return testRun;
    }

    /**
     * Sets the value of the testRun property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestRun }
     *     
     */
    public void setTestRun(TestRun value) {
        this.testRun = value;
    }

}
