//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.24 at 09:15:31 PM IST 
//


package utopia.sphnx.core.support.xmlmapping.testcases;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}iterationStep" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="iterationNumber" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="dataRow" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "iterationStep"
})
@XmlRootElement(name = "iteration")
public class Iteration {

    protected List<IterationStep> iterationStep;
    @XmlAttribute(name = "iterationNumber")
    protected Byte iterationNumber;
    @XmlAttribute(name = "dataRow")
    protected Byte dataRow;
    @XmlAttribute(name = "status")
    protected Byte status;

    /**
     * Gets the value of the iterationStep property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the iterationStep property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIterationStep().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IterationStep }
     * 
     * 
     */
    public List<IterationStep> getIterationStep() {
        if (iterationStep == null) {
            iterationStep = new ArrayList<IterationStep>();
        }
        return this.iterationStep;
    }

    /**
     * Gets the value of the iterationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getIterationNumber() {
        return iterationNumber;
    }

    /**
     * Sets the value of the iterationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setIterationNumber(Byte value) {
        this.iterationNumber = value;
    }

    /**
     * Gets the value of the dataRow property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getDataRow() {
        return dataRow;
    }

    /**
     * Sets the value of the dataRow property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setDataRow(Byte value) {
        this.dataRow = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setStatus(Byte value) {
        this.status = value;
    }

}
