//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.26 at 06:19:31 PM IST 
//


package utopia.sphnx.core.support.xmlmapping.testcases;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}TestStep"/>
 *         &lt;element ref="{}LOOP"/>
 *         &lt;element ref="{}END_LOOP"/>
 *       &lt;/choice>
 *       &lt;attribute name="TestCase" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="run" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="lastTest" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "testStepOrLOOPOrENDLOOP"
})
@XmlRootElement(name = "TestCase")
public class TestCase {

    @XmlElements({
        @XmlElement(name = "TestStep", type = TestStep.class),
        @XmlElement(name = "LOOP", type = LOOP.class),
        @XmlElement(name = "END_LOOP", type = ENDLOOP.class)
    })
    protected List<Object> testStepOrLOOPOrENDLOOP;
    @XmlAttribute(name = "TestCase")
    protected String testCase;
    @XmlAttribute(name = "run")
    protected String run;
    @XmlAttribute(name = "lastTest")
    protected String lastTest;

    @XmlAttribute(name = "MODE")
    protected String mode;

    /**
     * Gets the value of the testStepOrLOOPOrENDLOOP property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the testStepOrLOOPOrENDLOOP property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTestStepOrLOOPOrENDLOOP().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TestStep }
     * {@link LOOP }
     * {@link ENDLOOP }
     *
     * 
     */
    public List<Object> getTestStepOrLOOPOrENDLOOP() {
        if (testStepOrLOOPOrENDLOOP == null) {
            testStepOrLOOPOrENDLOOP = new ArrayList<Object>();
        }
        return this.testStepOrLOOPOrENDLOOP;
    }

    /**
     * Gets the value of the testCase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestCase() {
        return testCase;
    }

    /**
     * Sets the value of the testCase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestCase(String value) {
        this.testCase = value;
    }

    /**
     * Gets the value of the run property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRun() {
        return run;
    }

    /**
     * Sets the value of the run property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRun(String value) {
        this.run = value;
    }

    /**
     * Gets the value of the run property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLastTest() {
        return lastTest;
    }

    /**
     * Sets the value of the run property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLastTest(String value) {
        this.lastTest = value;
    }

    /**
     * Gets the value of the run property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMode() {
        return mode;
    }

    /**
     * Sets the value of the run property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMode(String value) {
        this.mode = value;
    }

}
